#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm test
npm run format
npm run lint
npm audit --fix
git add .

# prevent direct commits to main
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
      echo "You can't commit directly to main branch"
      exit 1
fi
